<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyTitle>Coding.Test</AssemblyTitle>
    <Product>Coding.Test</Product>
    <Copyright>Copyright ©  2025</Copyright>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Client\**" />
    <EmbeddedResource Remove="Client\**" />
    <None Remove="Client\**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="CqrsLite" Version="0.18.1" />
    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="10.0.1" />
    <PackageReference Include="Microsoft.CodeCoverage" Version="1.0.3" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.5.0" />
    <PackageReference Include="Microsoft.TestPlatform.ObjectModel" Version="17.10.0" />
    <PackageReference Include="Microsoft.TestPlatform.TestHost" Version="15.5.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="2.2.10" />
    <PackageReference Include="MSTest.TestFramework" Version="2.2.10" />
    <PackageReference Include="neurUL.Common" Version="0.2.1" />
    <PackageReference Include="neurUL.Common.Test" Version="0.1.7" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="System.Collections.Immutable" Version="8.0.0" />
    <PackageReference Include="System.IO.Pipelines" Version="10.0.1" />
    <PackageReference Include="System.Reflection.Metadata" Version="8.0.1" />
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.1.2" />
    <PackageReference Include="System.Text.Encodings.Web" Version="10.0.1" />
    <PackageReference Include="System.Text.Json" Version="10.0.1" />
    <PackageReference Include="xunit.abstractions" Version="2.0.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.7" />
    <PackageReference Include="xunit.v3.assert" Version="3.2.2" />
    <PackageReference Include="xunit.v3.core" Version="3.2.2" />
    <PackageReference Include="xunit.v3.extensibility.core" Version="3.2.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\main\Coding.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>
</Project>